version: "3.7"

services:
  #######################################
  # Insomnia: Openapi 2 kong declarative
  #######################################
  generate-kong-configs:
    image: kong/inso:latest
    working_dir: /app
    volumes:
      - .:/app
    command:
      generate config simple-api.yaml --output ./compose/kong/declarative/kong.yml --type declarative --verbose --tags api-example-v2

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong
    hostname: kong
    build:
      dockerfile: kong-with-plugin.Dockerfile
      context: compose
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./compose/kong/declarative:/usr/local/kong/declarative
      # - ./compose/kong/logs:/usr/local/kong/logs
      # - ./compose/kong/logs/log.txt:/usr/local/kong/logs/log.txt
      # - ./compose/kong/config/nginx.conf:/usr/local/kong/nginx.conf
      # - ./compose/kong/config/nginx-kong.conf:/usr/local/kong/nginx-kong.conf
    networks:
      - kong-net
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  simple-api-server:
    container_name: simple-api-server
    hostname: simple-api-server
    build:
      dockerfile: simple-api-server.Dockerfile
      context: compose
    ports:
      - "4000:4000"
    stdin_open: true
    tty:
      true
    networks:
      - kong-net

networks:
  kong-net:
    external: false
